sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t ubnt-mips-shadowsocks-libev .
  
script:
  - docker run -it --name ubnt-mips-shadowsocks-libev ubnt-mips-shadowsocks-libev
  - docker run -it -e ARCHITECH="mips64" --name ubnt-mips-shadowsocks-libev ubnt-mips-shadowsocks-libev
